# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  push :
    branches :
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --registry https://registry.npmjs.org
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      # - run: npm ci
      - run : rm .npmrc rm package.json mv npm.package.json package.json 
      - run : npm publish
      - run : npm install --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
